"""add indx

Revision ID: 5bb0143a79fa
Revises: f4546e5ff4c4
Create Date: 2024-02-12 13:28:06.676118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb0143a79fa'
down_revision: Union[str, None] = 'f4546e5ff4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('move_id_idx', table_name='moves')
    op.create_index('player_winning_move_id_idx', 'moves', ['player_id', 'id', 'is_winning_play'], unique=False)
    op.create_index('player_id_idx', 'player', ['id'], unique=False)
    op.create_index('roll_id_idx', 'rolls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('roll_id_idx', table_name='rolls')
    op.drop_index('player_id_idx', table_name='player')
    op.drop_index('player_winning_move_id_idx', table_name='moves')
    op.create_index('move_id_idx', 'moves', ['player_id', 'id', 'is_winning_play'], unique=False)
    # ### end Alembic commands ###
