"""index rename

Revision ID: b0675eac74e1
Revises: 5bb0143a79fa
Create Date: 2024-02-13 15:36:53.139408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0675eac74e1'
down_revision: Union[str, None] = '5bb0143a79fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('player_winning_move_id_idx', table_name='moves')
    op.create_index(op.f('ix_moves_player_id'), 'moves', ['player_id', 'id', 'is_winning_play'], unique=False)
    op.drop_index('player_id_idx', table_name='player')
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    op.drop_index('roll_id_idx', table_name='rolls')
    op.create_index(op.f('ix_rolls_id'), 'rolls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rolls_id'), table_name='rolls')
    op.create_index('roll_id_idx', 'rolls', ['id'], unique=False)
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.create_index('player_id_idx', 'player', ['id'], unique=False)
    op.drop_index(op.f('ix_moves_player_id'), table_name='moves')
    op.create_index('player_winning_move_id_idx', 'moves', ['player_id', 'id', 'is_winning_play'], unique=False)
    # ### end Alembic commands ###
